const strings = {
  app: {
    titulo: "Aplicativo de Tarefas",
    inicio: "Início",
    estatisticas: "Estatísticas",
    estatisticasRapidas: "Estatísticas Rápidas",
    concluidas: "Concluídas",
    filtros: "Filtros",
    adicionarTarefa: "Adicionar Tarefa",
    editarTarefa: "Editar Tarefa",
    salvar: "Salvar",
    visualizacaoLista: "Visualização em Lista",
    visualizacaoKanban: "Visualização Kanban",
  },
  tarefa: {
    titulo: "Título",
    descricao: "Descrição",
    categoria: "Categoria",
    prioridade: "Prioridade",
    dataVencimento: "Data de Vencimento",
    status: "Status",
  },
  categorias: {
    todas: "Todas as Categorias",
    pessoal: "Pessoal",
    trabalho: "Trabalho",
    compras: "Compras",
    outro: "Outro",
  },
  prioridades: {
    todas: "Todas as Prioridades",
    baixa: "Baixa",
    media: "Média",
    alta: "Alta",
  },
  status: {
    todos: "Todos os Status",
    ativas: "Ativas",
    concluidas: "Concluídas",
  },
  kanban: {
    aFazer: "A Fazer",
    emAndamento: "Em Andamento",
    concluidas: "Concluídas",
  },
  estatisticas: {
    conclusaoTarefas: "Conclusão de Tarefas",
    tarefasConcluidas: "Tarefas Concluídas",
    totalTarefas: "Total de Tarefas",
    taxaConclusao: "Taxa de Conclusão",
    categorias: "Categorias",
    prioridades: "Prioridades",
  },
  auth: {
    login: "Entrar",
    register: "Registrar",
    email: "E-mail",
    password: "Senha",
    confirmPassword: "Confirmar Senha",
    forgotPassword: "Esqueceu sua senha?",
    noAccount: "Não tem uma conta?",
    alreadyHaveAccount: "Já tem uma conta?",
    signUp: "Cadastre-se",
    signIn: "Entre",
    logout: "Sair",
    emailSent: "E-mail de confirmação enviado",
    checkEmail: "Verifique seu e-mail para confirmar sua conta",
    invalidCredentials: "E-mail ou senha inválidos",
    resetPassword: "Redefinir Senha",
    resetPasswordSuccess: "E-mail de redefinição enviado com sucesso!",
    resetPasswordError: "Erro ao enviar e-mail de redefinição",
  },
  profile: {
    title: "Perfil",
    email: "E-mail",
    name: "Nome",
    username: "Nome de usuário",
    website: "Website",
    viewProfile: "Ver Perfil",
  },
}

export default strings

